using CopperDevs.Windowing.SDL3.Data;

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member

// ReSharper disable once CheckNamespace
// ReSharper disable once InconsistentNaming
namespace CopperDevs.Windowing.SDL3;

public static unsafe partial class SDLAPI
{
    // public static void AcquireGPUCommandBuffer() => SDL_AcquireGPUCommandBuffer();
    // public static void AcquireGPUSwapchainTexture() => SDL_AcquireGPUSwapchainTexture();
    // public static void BeginGPUComputePass() => SDL_BeginGPUComputePass();
    // public static void BeginGPUCopyPass() => SDL_BeginGPUCopyPass();
    // public static void BeginGPURenderPass() => SDL_BeginGPURenderPass();
    // public static void BindGPUComputePipeline() => SDL_BindGPUComputePipeline();
    // public static void BindGPUComputeSamplers() => SDL_BindGPUComputeSamplers();
    // public static void BindGPUComputeStorageBuffers() => SDL_BindGPUComputeStorageBuffers();
    // public static void BindGPUComputeStorageTextures() => SDL_BindGPUComputeStorageTextures();
    // public static void BindGPUFragmentSamplers() => SDL_BindGPUFragmentSamplers();
    // public static void BindGPUFragmentStorageBuffers() => SDL_BindGPUFragmentStorageBuffers();
    // public static void BindGPUFragmentStorageTextures() => SDL_BindGPUFragmentStorageTextures();
    // public static void BindGPUGraphicsPipeline() => SDL_BindGPUGraphicsPipeline();
    // public static void BindGPUIndexBuffer() => SDL_BindGPUIndexBuffer();
    // public static void BindGPUVertexBuffers() => SDL_BindGPUVertexBuffers();
    // public static void BindGPUVertexSamplers() => SDL_BindGPUVertexSamplers();
    // public static void BindGPUVertexStorageBuffers() => SDL_BindGPUVertexStorageBuffers();
    // public static void BindGPUVertexStorageTextures() => SDL_BindGPUVertexStorageTextures();
    // public static void BlitGPUTexture() => SDL_BlitGPUTexture();
    // public static void CalculateGPUTextureFormatSize() => SDL_CalculateGPUTextureFormatSize();
    // public static void CancelGPUCommandBuffer() => SDL_CancelGPUCommandBuffer();
    // public static void ClaimWindowForGPUDevice() => SDL_ClaimWindowForGPUDevice();
    // public static void CopyGPUBufferToBuffer() => SDL_CopyGPUBufferToBuffer();
    // public static void CopyGPUTextureToTexture() => SDL_CopyGPUTextureToTexture();
    // public static void CreateGPUBuffer() => SDL_CreateGPUBuffer();
    // public static void CreateGPUComputePipeline() => SDL_CreateGPUComputePipeline();
    // public static void CreateGPUDevice() => SDL_CreateGPUDevice();
    // public static void CreateGPUDeviceWithProperties() => SDL_CreateGPUDeviceWithProperties();
    // public static void CreateGPUGraphicsPipeline() => SDL_CreateGPUGraphicsPipeline();
    // public static void CreateGPUSampler() => SDL_CreateGPUSampler();
    // public static void CreateGPUShader() => SDL_CreateGPUShader();
    // public static void CreateGPUTexture() => SDL_CreateGPUTexture();
    // public static void CreateGPUTransferBuffer() => SDL_CreateGPUTransferBuffer();
    // public static void DestroyGPUDevice() => SDL_DestroyGPUDevice();
    // public static void DispatchGPUCompute() => SDL_DispatchGPUCompute();
    // public static void DispatchGPUComputeIndirect() => SDL_DispatchGPUComputeIndirect();
    // public static void DownloadFromGPUBuffer() => SDL_DownloadFromGPUBuffer();
    // public static void DownloadFromGPUTexture() => SDL_DownloadFromGPUTexture();
    // public static void DrawGPUIndexedPrimitives() => SDL_DrawGPUIndexedPrimitives();
    // public static void DrawGPUIndexedPrimitivesIndirect() => SDL_DrawGPUIndexedPrimitivesIndirect();
    // public static void DrawGPUPrimitives() => SDL_DrawGPUPrimitives();
    // public static void DrawGPUPrimitivesIndirect() => SDL_DrawGPUPrimitivesIndirect();
    // public static void EndGPUComputePass() => SDL_EndGPUComputePass();
    // public static void EndGPUCopyPass() => SDL_EndGPUCopyPass();
    // public static void EndGPURenderPass() => SDL_EndGPURenderPass();
    // public static void GenerateMipmapsForGPUTexture() => SDL_GenerateMipmapsForGPUTexture();
    // public static void GetGPUDeviceDriver() => SDL_GetGPUDeviceDriver();
    // public static void GetGPUDriver() => SDL_GetGPUDriver();
    // public static void GetGPUShaderFormats() => SDL_GetGPUShaderFormats();
    // public static void GetGPUSwapchainTextureFormat() => SDL_GetGPUSwapchainTextureFormat();
    // public static void GetNumGPUDrivers() => SDL_GetNumGPUDrivers();
    // public static void GPUSupportsProperties() => SDL_GPUSupportsProperties();
    // public static void GPUSupportsShaderFormats() => SDL_GPUSupportsShaderFormats();
    // public static void GPUTextureFormatTexelBlockSize() => SDL_GPUTextureFormatTexelBlockSize();
    // public static void GPUTextureSupportsFormat() => SDL_GPUTextureSupportsFormat();
    // public static void GPUTextureSupportsSampleCount() => SDL_GPUTextureSupportsSampleCount();
    // public static void InsertGPUDebugLabel() => SDL_InsertGPUDebugLabel();
    // public static void MapGPUTransferBuffer() => SDL_MapGPUTransferBuffer();
    // public static void PopGPUDebugGroup() => SDL_PopGPUDebugGroup();
    // public static void PushGPUComputeUniformData() => SDL_PushGPUComputeUniformData();
    // public static void PushGPUDebugGroup() => SDL_PushGPUDebugGroup();
    // public static void PushGPUFragmentUniformData() => SDL_PushGPUFragmentUniformData();
    // public static void PushGPUVertexUniformData() => SDL_PushGPUVertexUniformData();
    // public static void QueryGPUFence() => SDL_QueryGPUFence();
    // public static void ReleaseGPUBuffer() => SDL_ReleaseGPUBuffer();
    // public static void ReleaseGPUComputePipeline() => SDL_ReleaseGPUComputePipeline();
    // public static void ReleaseGPUFence() => SDL_ReleaseGPUFence();
    // public static void ReleaseGPUGraphicsPipeline() => SDL_ReleaseGPUGraphicsPipeline();
    // public static void ReleaseGPUSampler() => SDL_ReleaseGPUSampler();
    // public static void ReleaseGPUShader() => SDL_ReleaseGPUShader();
    // public static void ReleaseGPUTexture() => SDL_ReleaseGPUTexture();
    // public static void ReleaseGPUTransferBuffer() => SDL_ReleaseGPUTransferBuffer();
    // public static void ReleaseWindowFromGPUDevice() => SDL_ReleaseWindowFromGPUDevice();
    // public static void SetGPUAllowedFramesInFlight() => SDL_SetGPUAllowedFramesInFlight();
    // public static void SetGPUBlendConstants() => SDL_SetGPUBlendConstants();
    // public static void SetGPUBufferName() => SDL_SetGPUBufferName();
    // public static void SetGPUScissor() => SDL_SetGPUScissor();
    // public static void SetGPUStencilReference() => SDL_SetGPUStencilReference();
    // public static void SetGPUSwapchainParameters() => SDL_SetGPUSwapchainParameters();
    // public static void SetGPUTextureName() => SDL_SetGPUTextureName();
    // public static void SetGPUViewport() => SDL_SetGPUViewport();
    // public static void SubmitGPUCommandBuffer() => SDL_SubmitGPUCommandBuffer();
    // public static void SubmitGPUCommandBufferAndAcquireFence() => SDL_SubmitGPUCommandBufferAndAcquireFence();
    // public static void UnmapGPUTransferBuffer() => SDL_UnmapGPUTransferBuffer();
    // public static void UploadToGPUBuffer() => SDL_UploadToGPUBuffer();
    // public static void UploadToGPUTexture() => SDL_UploadToGPUTexture();
    // public static void WaitAndAcquireGPUSwapchainTexture() => SDL_WaitAndAcquireGPUSwapchainTexture();
    // public static void WaitForGPUFences() => SDL_WaitForGPUFences();
    // public static void WaitForGPUIdle() => SDL_WaitForGPUIdle();
    // public static void WaitForGPUSwapchain() => SDL_WaitForGPUSwapchain();
    // public static void WindowSupportsGPUPresentMode() => SDL_WindowSupportsGPUPresentMode();
    // public static void WindowSupportsGPUSwapchainComposition() => SDL_WindowSupportsGPUSwapchainComposition();
}